---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups: ["gateway.kyma-project.io"]
    resources: ["gates", "gates/status"]
    verbs: ["*"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["create", "delete", "get", "patch", "list", "watch"]
