---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough-bad-host
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  auth:
    name: ALLOW
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      scopes: []
      methods: ["GET"]
      accessStrategy:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough-bad-host
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  auth:
    name: ALLOW
  gateway: short-name-gateway
  rules:
    - path: /.*
      scopes: []
      methods: ["GET"]
      accessStrategy:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: gate-no-rules
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  auth:
    name: ALLOW
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: gate-multiple-hosts
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  auth:
    name: ALLOW
  gateway: short-name-gateway
  rules:
    - path: /.*
      scopes: []
      methods: ["GET"]
      accessStrategy:
        - handler: noop
      mutators: []
    - path: /foo
      scopes: []
      methods: ["GET"]
      accessStrategy:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough-secured-scopes
spec:
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: ALLOW
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      scopes: ["foo", "bar"]
      methods: ["GET"]
