---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: passthrough-bad-host
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: passthrough-bad-gateway
spec:
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  gateway: short-name-gateway
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: gate-no-rules
spec:
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules: []
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: blocklisted-service
spec:
  service:
    host: kubernetes.kyma.local
    name: kubernetes
    port: 443
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET", "POST"]
      accessStrategies:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: not-allowlisted-domain
spec:
  service:
    host: foo.some-fancy-domain.xyz
    name: foo
    port: 443
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET", "POST"]
      accessStrategies:
        - handler: noop
      mutators: []
