---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: passthrough-bad-host
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: passthrough-bad-host
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  gateway: short-name-gateway
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: gate-no-rules
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules: []
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: gate-multiple-hosts
spec:
  service:
    host: https://imgur.com
    name: httpbin
    port: 8000
  gateway: short-name-gateway
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators: []
    - path: /foo
      methods: ["GET"]
      accessStrategies:
        - handler: noop
      mutators: []
