---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough-bad-host
spec:
  service:
    host: https://imgur.com
    name: imgur
    port: 443
  auth: 
    name: PASSTHROUGH
  gateway: some-gateway.some-namespace
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough-bad-gateway
spec:
  service:
    host: imgur.com
    name: imgur
    port: 443
  auth: 
    name: PASSTHROUGH
  gateway: short-name-gateway
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth-no-paths
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: imgur.com
    name: imgur
    port: 443
  auth: 
    name: OAUTH
    config:
      paths: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth-bad-paths
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: imgur.com
    name: imgur
    port: 443
  auth: 
    name: OAUTH
    config:
      paths:
      - path: /foo
        scopes: [foo, bar]
        methods: [GET]
      - path: /foo
        scopes: [foo]
        methods: [POST]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-bad-issuer
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth: 
    name: JWT
    config:
      issuer: not-a-valid-url
      jwks: []
      mode: 
        name: ALL
        config:
          scopes: ["foo", "bar"]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-bad-mode
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth: 
    name: JWT
    config:
      issuer: http://dex.kyma.local
      jwks: []
      mode: 
        name: FOO
        config:
          foo: bar
