---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough
spec:
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: PASSTHROUGH
  gateway: kyma-gateway.kyma-system.svc.cluster.local
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-all-no-scopes
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth:
    name: JWT
    config:
      issuer: http://dex.kyma.local
      jwks: []
      mutators: []
      mode:
        name: ALL
  paths:
    - path: /.*
      scopes: []
      methods: ["GET"]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-all-mutators
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth:
    name: JWT
    config:
      issuer: http://dex.kyma.local
      jwks: []
      mutators: 
        - handler: noop
      mode:
        name: ALL
  paths:
    - path: /.*
      scopes: ["foo", "bar"]
      methods: ["GET"]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-all-with-scopes
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth: 
    name: JWT
    config:
      issuer: http://dex.kyma.local
      jwks: []
      mutators: []
      mode: 
        name: ALL
  paths:
    - path: /.*
      scopes: ["foo", "bar"]
      methods: ["GET"]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: OAUTH
    config:
      mutators: []
  paths:
    - path: /.*
      scopes: ["read"]
      methods: ["GET"]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth-mutators
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: OAUTH
    config:
      mutators:
        - handler: noop
          config: {}
  paths:
    - path: /.*
      scopes: ["read"]
      methods: ["GET"]
