---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough-unsecured
spec:
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: ALLOW
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      scopes: []
      methods: ["GET"]
      accessStrategy:
        - handler: noop
      mutators: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: passthrough-secured-mutators
spec:
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: ALLOW
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategy:
        - handler: noop
      mutators:
        - handler: noop
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-all-no-scopes
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth:
    name: JWT
    config:
      issuer: http://dex.kyma.local
      jwks: []
  rules:
    - path: /.*
      methods: ["GET"]
      mutators: []
      accessStrategy:
        - handler: jwt
          config:
            trusted_issuers: ["http://dex.kyma.local"]
            required_scope: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-all-mutators
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth:
    name: JWT
    config:
      issuer: http://dex.kyma.local
      jwks: []
  rules:
    - path: /.*
      methods: ["GET"]
      mutators:
        - handler: noop
      accessStrategy:
        - handler: jwt
          config:
            trusted_issuers: ["http://dex.kyma.local"]
            required_scope: []
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: jwt-all-with-scopes
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: foo-service
    port: 8080
    host: foo.bar
  auth: 
    name: JWT
    config:
      issuer: http://dex.kyma.local
      jwks: []
  rules:
    - path: /.*
      methods: ["GET"]
      mutators: []
      accessStrategy:
        - handler: jwt
          config:
            trusted_issuers: ["http://dex.kyma.local"]
            required_scope: ["foo", "bar"]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: OAUTH
  rules:
    - path: /.*
      scopes: ["read"]
      methods: ["GET"]
      mutators: []
      accessStrategy:
        - handler: oauth2_introspection
          config:
            required_scope: ["foo", "bar"]
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth-mutators
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  auth:
    name: OAUTH
  rules:
    - path: /.*
      methods: ["GET"]
      mutators:
        - handler: noop
          config: {}
      accessStrategy:
        - handler: oauth2_introspection
          config:
            required_scope: []
