replicaCount: 1

rbacJob:
  image:
    repository: eu.gcr.io/kyma-project/test-infra/alpine-kubectl
    tag: "v20190325-ff66a3a"

image:
  repository: eu.gcr.io/kyma-project/incubator/develop/api-gateway-controller
  tag: "2a721826"
  # Image pull policy
  pullPolicy: IfNotPresent

deployment:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

config:
  oathkeeper:
    service: ory-oathkeeper
    port: 4455
  jwksURI: https://example.com/.well-known/jwks.json
  serviceBlackList:
    - kubernetes
    - kube-dns
  domainWhiteList:
    - kyma.local
  # If you want to specify CORS config yourself, uncomment the following lines and provide custom values
#  cors:
#  # values listed below will be used to set corsPolicy in created VirtualServices (https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#CorsPolicy)
#  # a value may be a single string (e.g. "*", "console.kyma.local") or a comma-separated list of strings (e.g. "https://console.kyma.local,https://lambdas-ui.kyma.local", "GET,POST,PUT,DELETE")
#    allowOrigin: ""
#    allowMethods: ""
#    allowHeaders: ""

  # Node labels for pod assignment.
  nodeSelector: {}
  # If you do want to specify node labels, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
  #   foo: bar

  # Configure node tolerations.
  tolerations: []
  annotations: {}

# Configure node affinity
affinity: {}