replicaCount: 1

rbacJob:
  image:
    repository: eu.gcr.io/kyma-project/tpi/k8s-tools
    tag: "20210504-12243229"

image:
  repository: eu.gcr.io/kyma-project/incubator/develop/api-gateway-controller
  tag: "c1d35a0c"
  # Image pull policy
  pullPolicy: IfNotPresent

deployment:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

config:
  oathkeeper:
    service: ory-oathkeeper
    port: 4455
  jwksURI: https://example.com/.well-known/jwks.json
  serviceBlockList:
    default:
      - kubernetes
    kube-system:
      - kube-dns
  domainAllowList:
    - kyma.local
  cors: # values listed below will be used to set corsPolicy in created VirtualServices (https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#CorsPolicy)
    allowOrigins:
      regex:
        - ".*"
    allowMethods: # no possibility to use "*"
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    allowHeaders: # "*" is not yet supported by all browsers
      - "Authorization"
      - "Content-Type"
      - "*"

  # Node labels for pod assignment.
  nodeSelector: {}
  # If you do want to specify node labels, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'annotations:'.
  #   foo: bar

  # Configure node tolerations.
  tolerations: []
  annotations: {}

# Configure node affinity
affinity: {}
