apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: api-gateway-manager-role
rules:
- apiGroups:
  - gateway.kyma-project.io
  resources:
  - gates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - gateway.kyma-project.io
  resources:
  - gates/status
  verbs:
  - get
  - update
  - patch
