apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway-leader-election-rolebinding
  namespace: api-gateway-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-gateway-leader-election-role
subjects:
- kind: ServiceAccount
  name: api-gateway-api-gateway-sa
  namespace: api-gateway-system
